<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <AssemblyName>UnityEngine.UI</AssemblyName>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="UnityEngine.Modules" Version="2020.3.35" />
    <Compile Include="../../cameraunlock-core/csharp/stubs/UnityUIStubs.cs" />
  </ItemGroup>
</Project>
